### ISSUE TITLE
Investigate why id_token response type is not supported in implicit grant

### ISSUE THREAD

**Issue by aeneasr** [ory/fosite-example#10]

**Comment by tobowers** [comment]
noting that it succeeds (returning two tokens) if you reverse the order. so id_token%20token works but not token%20id_token

**Comment by mirazero** [comment]
How do I use storage with postgresql, not memory storage?

**Comment by arekkas** [comment]
@mirazero this is not the right place to ask, please create a new issue to ask unrelated questions to the original issue.

**Comment by mirazero** [comment]
sorry, I have a mistake. thanks.

**Comment by mitar** [comment]
`token id_token` works now for me with 0.31 version of fosite.
