### ISSUE TITLE
How do I use storage with postgresql, not memory storage?

### ISSUE THREAD

**Issue by mirazero** [ory/fosite-example#11]
This is very nice library.
I am getting a lot of help from this library.
I want to use a postgresql as storage.
It's very complicated to me. Could you please advice to me about that ?

thanks

**Comment by arekkas** [comment]
You will need to rewrite [this](https://github.com/ory/fosite/blob/master/storage/memory.go) to use `database/sql` and PostgreSQL.

**Comment by gauravbansal74** [comment]
@arekkas Can you help us to provide any reference for "How to user storage with PostgreSQL"?

@mirazero Can you help if you have implemented?

**Comment by arekkas** [comment]
@gauravbansal74 my advice is to use https://github.com/ory/hydra

**Comment by gauravbansal74** [comment]
@arekkas  Hydra has limitation. so we don't want to have those [limitations](https://www.gitbook.com/book/ory/hydra/details) in our applications.

**Comment by arekkas** [comment]
If you are referring to the password credentials grant, which you probably are, I advise you **strongly and forecefully** to throw away that requirement. It's ancient, insecure, bad practice.

In any case, Hydra ships a SQL store for fosite, see: https://github.com/ory/hydra/blob/master/oauth2/fosite_store_sql.go

**Comment by shamimevatix** [comment]
> If you are referring to the password credentials grant, which you probably are, I advise you **strongly and forecefully** to throw away that requirement. It's ancient, insecure, bad practice.
> 
> In any case, Hydra ships a SQL store for fosite, see: https://github.com/ory/hydra/blob/master/oauth2/fosite_store_sql.go

The link no longer exists.

**Comment by shamimevatix** [comment]
I also need the postgresql storage urgently. Can anyone please help me with any other library? Can't see the SQL storage in Hydra. Even chatgpt is giving me wrong info.
