### ISSUE TITLE
you should not use gorequest library with http connections leak

### ISSUE THREAD

**Issue by melkus** [ory/fosite-example#12]
Please do not use gorequest in your demo, because other people may want to use samples from demo in production.

gorequest library has http connections leak:
https://github.com/parnurzeal/gorequest/issues/75
And many other issues that nobody work on. Probably project is dead.

**Comment by arekkas** [comment]
The commit history is [very active](https://github.com/parnurzeal/gorequest/commits/develop) so I'm not sure where "The project is dead" comes from, but feel free to replace gorequest with standard a http client in a PR!
