### ISSUE TITLE
error on go install 

### ISSUE THREAD

**Issue by vvhh2002** [ory/fosite-example#5]
github.com/ory/fosite-example/vendor/github.com/ory/fosite/compose
vendor/github.com/ory/fosite/compose/compose_openid.go:28: cannot use "github.com/ory-am/fosite/handler/oauth2".AuthorizeImplicitGrantTypeHandler literal (type *"github.com/ory-am/fosite/handler/oauth2".AuthorizeImplicitGrantTypeHandler) as type *"github.com/ory/fosite/handler/oauth2".AuthorizeImplicitGrantTypeHandler in field value
vendor/github.com/ory/fosite/compose/compose_openid.go:47: cannot use "github.com/ory-am/fosite/handler/oauth2".AuthorizeExplicitGrantHandler literal (type *"github.com/ory-am/fosite/handler/oauth2".AuthorizeExplicitGrantHandler) as type *"github.com/ory/fosite/handler/oauth2".AuthorizeExplicitGrantHandler in field value
vendor/github.com/ory/fosite/compose/compose_openid.go:53: cannot use "github.com/ory-am/fosite/handler/oauth2".AuthorizeImplicitGrantTypeHandler literal (type *"github.com/ory-am/fosite/handler/oauth2".AuthorizeImplicitGrantTypeHandler) as type *"github.com/ory/fosite/handler/oauth2".AuthorizeImplicitGrantTypeHandler in field value
vendor/github.com/ory/fosite/compose/compose_strategy.go:21: cannot use "github.com/ory-am/fosite/token/hmac".HMACStrategy literal (type *"github.com/ory-am/fosite/token/hmac".HMACStrategy) as type *"github.com/ory/fosite/token/hmac".HMACStrategy in field value
vendor/github.com/ory/fosite/compose/compose_strategy.go:31: cannot use "github.com/ory-am/fosite/token/jwt".RS256JWTStrategy literal (type *"github.com/ory-am/fosite/token/jwt".RS256JWTStrategy) as type *"github.com/ory/fosite/token/jwt".RS256JWTStrategy in field value
vendor/github.com/ory/fosite/compose/compose_strategy.go:39: cannot use "github.com/ory-am/fosite/token/jwt".RS256JWTStrategy literal (type *"github.com/ory-am/fosite/token/jwt".RS256JWTStrategy) as type *"github.com/ory/fosite/token/jwt".RS256JWTStrategy in field value
# github.com/ory/fosite-example/vendor/github.com/ory/fosite/handler/openid
vendor/github.com/ory/fosite/handler/openid/flow_hybrid.go:58: cannot use ar (type "github.com/ory-am/fosite".AuthorizeRequester) as type "github.com/ory/fosite".Requester in argument to c.AuthorizeExplicitGrantHandler.AuthorizeCodeStrategy.GenerateAuthorizeCode:
	"github.com/ory-am/fosite".AuthorizeRequester does not implement "github.com/ory/fosite".Requester (wrong type for GetClient method)
		have GetClient() "github.com/ory-am/fosite".Client
		want GetClient() "github.com/ory/fosite".Client
vendor/github.com/ory/fosite/handler/openid/flow_hybrid.go:61: cannot use ar (type "github.com/ory-am/fosite".AuthorizeRequester) as type "github.com/ory/fosite".Requester in argument to c.AuthorizeExplicitGrantHandler.AuthorizeCodeGrantStorage.CreateAuthorizeCodeSession:
	"github.com/ory-am/fosite".AuthorizeRequester does not implement "github.com/ory/fosite".Requester (wrong type for GetClient method)
		have GetClient() "github.com/ory-am/fosite".Client
		want GetClient() "github.com/ory/fosite".Client
vendor/github.com/ory/fosite/handler/openid/flow_hybrid.go:72: cannot use ([]byte)(base64.URLEncoding.EncodeToString(([]byte)(hash[:c.Enigma.GetSigningMethodLength() / 2]))) (type []byte) as type string in assignment
vendor/github.com/ory/fosite/handler/openid/flow_hybrid.go:78: too many arguments in call to c.AuthorizeImplicitGrantTypeHandler.IssueImplicitAccessToken
	have ("github.com/ory/fosite-example/vendor/golang.org/x/net/context".Context, *http.Request, "github.com/ory-am/fosite".AuthorizeRequester, "github.com/ory-am/fosite".AuthorizeResponder)
	want ("context".Context, "github.com/ory/fosite".AuthorizeRequester, "github.com/ory/fosite".AuthorizeResponder)
vendor/github.com/ory/fosite/handler/openid/flow_hybrid.go:87: cannot use ([]byte)(base64.URLEncoding.EncodeToString(([]byte)(hash[:c.Enigma.GetSigningMethodLength() / 2]))) (type []byte) as type string in assignment
vendor/github.com/ory/fosite/handler/openid/flow_implicit.go:56: too many arguments in call to c.AuthorizeImplicitGrantTypeHandler.IssueImplicitAccessToken
	have ("github.com/ory/fosite-example/vendor/golang.org/x/net/context".Context, *http.Request, "github.com/ory-am/fosite".AuthorizeRequester, "github.com/ory-am/fosite".AuthorizeResponder)
	want ("context".Context, "github.com/ory/fosite".AuthorizeRequester, "github.com/ory/fosite".AuthorizeResponder)
vendor/github.com/ory/fosite/handler/openid/flow_implicit.go:66: cannot use ([]byte)(base64.URLEncoding.EncodeToString(([]byte)(hash[:c.RS256JWTStrategy.GetSigningMethodLength() / 2]))) (type []byte) as type string in assignment

**Comment by arekkas** [comment]
Try

```
$ go get -d github.com/ory/fosite-example
$ cd $GOPATH/src/github.com/ory/fosite-example
$ glide install
$ go install .
```
